### ISSUE TITLE
Distribute using krew?

### ISSUE THREAD

**Issue by ahmetb** [mousavian/kubectl-rotate-pods#1]
https://krew.dev makes it very easy to distribute and release upgrades to these plugins.

**Comment by mousavian** [comment]
Hey @ahmetb,
I know about krew. In fact, I wrote this plugin after I listened to kubernetes podcast where you talked about krew :) 

But actually this feature already exists in kubectl itself: `kubectl rollout restart`. Hence, I didn't request to merge it into krew.

Cheers

**Comment by ahmetb** [comment]
Thanks. Never imagined that command is actually for power-cycling the pods.
